//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Bullets_H
#define METASPRITE_Bullets_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Bullets_TILE_ORIGIN 0
#define Bullets_TILE_H 16
#define Bullets_WIDTH 8
#define Bullets_HEIGHT 8
#define Bullets_TILE_COUNT 8
#define Bullets_PALETTE_COUNT 7
#define Bullets_PIVOT_X 4
#define Bullets_PIVOT_Y 4
#define Bullets_PIVOT_W 8
#define Bullets_PIVOT_H 8

BANKREF_EXTERN(Bullets)

extern const palette_color_t Bullets_palettes[28];
extern const uint8_t Bullets_tiles[128];

extern const metasprite_t* const Bullets_metasprites[4];

#endif